### PR TITLE
Make logging more tolerable

### PR DESCRIPTION
**Pull request by minecrafter**
Until we move to log4j, this will make logging less of a hassle to deal with.

This will reduce the maximum log size (16MB to 4MB) and will not add entries to existing log files (it will rotate them instead).

I'd like some more opinion on this.

### CODE REVIEW

**Comment by Techcable** [comment]
I like the idea of rotation, but not reducing log size.

**Comment by kashike** [comment]
I don't really see the point of changing the log file size, but I do like the idea of rotation.

**Comment by RhvsW** [comment]
If your log is 4MB of pure text it should probably be rotated.

**Comment by minecrafter** [comment]
@kashike @Techcable would 8MB be better?

**Comment by kashike** [comment]
@minecrafter 8MB seems acceptable I suppose

**Comment by harrydevane** [comment]
@minecrafter 8MB default would work, perhaps include a system property to allow more advanced users to change it?

**Comment by minecrafter** [comment]
I don't believe we need to be putting every option in a system property. Eventually it will get quite cluttered.

8MB is the maximum we should go, and is probably far beyond a reasonable limit for most log file sizes in my opinion.

**Comment by minecrafter** [comment]
Going to merge this.

**Pull request closed without merging**
