### PR TITLE
Add per-server ip forwarding and ability to add shared secrets

### PR DESCRIPTION
**Pull request by kashike**

### CODE REVIEW

**Comment by Techcable** [comment]
:-1: shared 'secrets' are sent in plaintext

**Comment by Ichbinjoe** [comment]
I feel like the first two should be confirmed with an HMAC signature...
Would need to look up the correct way to do it however I'm pretty sure that
way would work fine.

**Comment by Techcable** [comment]
Would need to do a HMAC256 over the hostname (including the uuid and forwarding info), and we have to add a timestamp. Preferably the server would 'challenge' the bungee with random data (since otherwise the attacker could just re-send previous handhsakes), but a timestamp would be relatively safe, as we could preform various validations on it.

**Comment by Ichbinjoe** [comment]
I think timestamp would work fine. Most servers have ntp capabilities, and we can check this at startup using something like icanhazepoch.com. (https://github.com/Ichbinjoe/MCAuthenticator/blob/986bfc4bb794d0c2667e7135b287a7c56cfa5099/src/main/java/com/aaomidi/mcauthenticator/auth/RFC6238.java#L135)

**Comment by punkeel** [comment]
Sorry to ask, but is this really "required"?
I mean, I understand a plugin might add this feature, as a plugin would handle it Spigot-side too … but I quite don't understand why it would be WaterFall's job.
(Sorry if this sounds harsh, that's not my purpose at all)

What I do think is great: the ability to enable/disable the IP Forward feature on an user level, and letting plugins set custom handshake data (data, not "shared secret").

Said another way: I like this, but I dislike your use of the word "secret"

**Comment by Techcable** [comment]
Yeah, maybe we should add a handshake event?

**Comment by Ichbinjoe** [comment]
@PunKeel What terminology would you instead prefer? A handshake event simply opens up the possibility for lots of wrong implementations of actual security.

I really think the HMAC mechanism discussed above will work perfectly.

As for other information being passed along, I really think that information should be carried over other channels, and not the handshake.

**Comment by punkeel** [comment]
@Ichbinjoe I agree with you.

> I really think that information should be carried over other channels, and not the handshake.

For the sake of not agreeing, I could say the same of this PR ;-)

**Pull request closed without merging**
